version: '3.7'
services:
  bdd:
    build:
        context: ./docker/postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
